//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Id_ev { get; set; }
        public string Name_events { get; set; }
        public System.DateTime Date { get; set; }
        public int Days { get; set; }
        public string ImageName { get; set; }
        public byte[] Image { get; set; }
        public int IdCity { get; set; }
    
        public virtual City City { get; set; }
        public virtual Event_act Event_act { get; set; }
    }
}
