//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id_act { get; set; }
        public int IdEvent_act { get; set; }
        public System.DateTime Date { get; set; }
        public int Days { get; set; }
        public string ActivName { get; set; }
        public int Day { get; set; }
        public System.TimeSpan Time { get; set; }
        public int IdModer { get; set; }
        public int Jury_1 { get; set; }
        public Nullable<int> Jury_2 { get; set; }
        public Nullable<int> Jury_3 { get; set; }
        public Nullable<int> Jury_4 { get; set; }
        public Nullable<int> Jury_5 { get; set; }
        public int Winner { get; set; }
    
        public virtual Event_act Event_act { get; set; }
        public virtual General General { get; set; }
        public virtual General General1 { get; set; }
        public virtual General General2 { get; set; }
        public virtual General General3 { get; set; }
        public virtual General General4 { get; set; }
        public virtual General General5 { get; set; }
        public virtual General General6 { get; set; }
    }
}
